# Generated by Django 4.0.4 on 2022-07-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=100, null=True)),
                ('customerPassword', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
