# Generated by Django 4.0.4 on 2022-07-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customer_cartnumber_customer_country_customer_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.TextField(null=True),
        ),
    ]
